normal1: 'lightest_grey darker_blue'
normal2: 'lightest_grey dark_grey'
normal3: 'lightest_grey darkest_grey'
normal4: 'darkest_grey light_grey'
normal5: 'lightest_grey dark_grey'
normalError: 'lightest_grey dark_red'
normalWarning: 'darkest_grey light_orange'
inactive1: 'lightest_grey darkest_grey'
inactive2: 'lightest_grey dark_grey'
inactive3: 'lightest_grey darkest_grey'
inactive4: 'darkest_grey light_grey'
inactive5: 'lightest_grey dark_grey'
insert1: 'darkest_grey dirty_green'
insert2: 'lightest_grey dark_grey'
insert3: 'lightest_grey darkest_grey'
insert4: 'darkest_grey light_grey'
insert5: 'lightest_grey dark_grey'
replace1: 'light_pink dark_red'
replace2: 'lightest_grey dark_grey'
replace3: 'lightest_grey darkest_grey'
replace4: 'darkest_grey light_grey'
replace5: 'lightest_grey dark_grey'
visual1: 'darkest_grey light_orange'
visual2: 'lightest_grey dark_grey'
visual3: 'lightest_grey darkest_grey'
visual4: 'darkest_grey light_grey'
visual5: 'lightest_grey dark_grey'
tablineLeft: 'lightest_grey darkest_grey'
tablineSelected: 'lightest_grey darker_blue'
tablineMiddle: 'darkest_grey darkest_grey'
tablineRight: 'lightest_grey darkest_grey'
