cssPseudoClassFn: 'dark_pink'
cssPageAttr: '@cssBoxAttr'
cssColorAttr: '@cssBoxAttr'
cssComment: '' # Comment
cssVendor: '' # Comment
cssHacks: '' # Comment
cssTagName: 'light_blue' # Statement
cssDeprecated: '' # Error
cssSelectorOp: '' # Special
cssSelectorOp2: '' # Special
cssAttrComma: '' # Special
cssAnimationProp: '' # cssProp
cssBackgroundProp: 'light_green' # cssProp
cssBorderProp: 'light_green' # cssProp
cssBoxProp: 'light_green' # cssProp
cssColorProp: 'light_green' # cssProp
cssContentForPagedMediaProp: '' # cssProp
cssDimensionProp: 'light_green' # cssProp
cssFlexibleBoxProp: '' # cssProp
cssFontProp: 'light_green' # cssProp
cssGeneratedContentProp: '' # cssProp
cssGridProp: '' # cssProp
cssHyerlinkProp: '' # cssProp
cssLineboxProp: '' # cssProp
cssListProp: '' # cssProp
cssMarqueeProp: '' # cssProp
cssMultiColumnProp: '' # cssProp
cssPagedMediaProp: '' # cssProp
cssPositioningProp: 'light_green' # cssProp
cssPrintProp: '' # cssProp
cssRubyProp: '' # cssProp
cssSpeechProp: '' # cssProp
cssTableProp: '' # cssProp
cssTextProp: 'light_green' # cssProp
cssTransformProp: 'light_green' # cssProp
cssTransitionProp: 'light_green' # cssProp
cssUIProp: 'light_green' # cssProp
cssIEUIProp: '' # cssProp
cssAuralProp: '' # cssProp
cssRenderProp: '' # cssProp
cssMobileTextProp: '' # cssProp
cssAnimationAttr: '' # cssAttr
cssBackgroundAttr: 'light_yellow' # cssAttr
cssBorderAttr: 'light_yellow' # cssAttr
cssBoxAttr: 'light_yellow' # cssAttr
cssContentForPagedMediaAttr: '' # cssAttr
cssDimensionAttr: 'light_yellow' # cssAttr
cssFlexibleBoxAttr: '' # cssAttr
cssFontAttr: 'light_yellow' # cssAttr
cssGeneratedContentAttr: '' # cssAttr
cssGridAttr: '' # cssAttr
cssHyerlinkAttr: '' # cssAttr
cssLineboxAttr: '' # cssAttr
cssListAttr: '' # cssAttr
cssMarginAttr: '' # cssAttr
cssMarqueeAttr: '' # cssAttr
cssMultiColumnAttr: '' # cssAttr
cssPaddingAttr: '' # cssAttr
cssPagedMediaAttr: '' # cssAttr
cssPositioningAttr: 'light_yellow' # cssAttr
cssGradientAttr: '' # cssAttr
cssPrintAttr: '' # cssAttr
cssRubyAttr: '' # cssAttr
cssSpeechAttr: '' # cssAttr
cssTableAttr: '' # cssAttr
cssTextAttr: 'light_yellow' # cssAttr
cssTransformAttr: '' # cssAttr
cssTransitionAttr: 'light_yellow' # cssAttr
cssUIAttr: 'light_yellow' # cssAttr
cssIEUIAttr: '' # cssAttr
cssAuralAttr: '' # cssAttr
cssRenderAttr: '' # cssAttr
cssCommonAttr: 'light_yellow' # cssAttr
cssPseudoClassId: 'light_orange' # PreProc
cssPseudoClassLang: '' # Constant
cssValueLength: 'light_yellow' # Number
cssValueInteger: '' # Number
cssValueNumber: 'light_yellow' # Number
cssValueAngle: '' # Number
cssValueTime: '' # Number
cssValueFrequency: '' # Number
cssFunction: '' # Constant
cssURL: '' # String
cssFunctionName: '' # Function
cssFunctionComma: '' # Function
cssColor: '' # Constant
cssIdentifier: 'yellow' # Function
cssInclude: 'white' # Include
cssIncludeKeyword: 'dark_orange' # atKeyword
cssImportant: '' # Special
cssBraces: 'white' # Function
cssBraceError: '' # Error
cssError: '' # Error
cssUnicodeEscape: '' # Special
cssStringQQ: '' # String
cssStringQ: '' # String
cssAttributeSelector: '' # String
cssMedia: '' # atKeyword
cssMediaType: 'dirty_pink' # Special
cssMediaComma: '' # Normal
cssMediaKeyword: 'dark_orange' # Statement
cssMediaProp: 'light_green' # cssProp
cssMediaAttr: '' # cssAttr
cssPage: '' # atKeyword
cssPagePseudo: '' # PreProc
cssPageMargin: '' # atKeyword
cssPageProp: 'light_green' # cssProp
cssKeyFrame: '' # atKeyword
cssKeyFrameSelector: '' # Constant
cssFontDescriptor: '' # Special
cssFontDescriptorFunction: '' # Constant
cssFontDescriptorProp: '' # cssProp
cssFontDescriptorAttr: '' # cssAttr
cssUnicodeRange: '' # Constant
cssClassName: 'green' # Function
cssClassNameDot: '' # Function
cssProp: '' # StorageClass
cssAttr: '' # Constant
cssUnitDecorators: 'dark_orange' # Number
cssNoise: '' # Noise
atKeyword: '' # PreProc
