pythonOperator: '@Statement' # Operator
pythonStatement: '' # Statement
pythonConditional: '' # Conditional
pythonRepeat: '' # Repeat
pythonException: '' # Exception
pythonInclude: '' # Include
pythonDecorator: '' # Define
pythonFunction: '' # Function
pythonComment: '' # Comment
pythonTodo: '' # Todo
pythonString: '' # String
pythonRawString: '' # String
pythonQuotes: '' # String
pythonTripleQuotes: '' # pythonQuotes
pythonEscape: '' # Special
pythonNumber: '' # Number
pythonBuiltin: '' # Function
pythonExceptions: '' # Structure
pythonSpaceError: '' # Error
pythonDoctest: '' # Special
pythonDoctestValue: '' # Define
