FortifyAuditPaneHelp: '@Comment'
FortifyAuditPaneHelpKey: '@Identifier'
FortifyAuditPaneHelpTitle: '@PreProc'
FortifyAuditPaneCategoryCount: '@Title'
FortifyAuditPaneDigit: '@Text'
FortifyAuditPaneInfo: '@Title'
FortifyAuditPaneTraces: '@Title'
FortifyAuditPaneIssue: '@Statement'
FortifyAuditPaneFoldIcon: '@Title'
FortifyAuditPaneAltFoldIcon: '@Keyword'
FortifyAuditPaneBracket: '@Title'
FortifyAuditPaneRule: '@Title'
FortifyAuditPaneFact: '@Type'
FortifyAuditPaneInCallIcon: 'green'
FortifyAuditPaneInOutCallIcon: 'blue'
FortifyAuditPaneOutCallIcon: 'red'
FortifyAuditPaneReadGlobalIcon: 'dark_orange'
FortifyAuditPaneAssignGlobalIcon: 'dark_orange' 
FortifyAuditPaneAssignIcon : 'dark_orange'       
FortifyAuditPaneReturnIcon: 'yellow'
FortifyAuditPaneExternalEntry: 'yellow'       
FortifyAuditPaneSeparator: 'yellow'          
FortifyAuditPaneRuleIcon: 'yellow'           
FortifyAuditPaneFile: 'dark_grey' 
FortifyAuditPaneBranchTakenIcon: 'green'    
FortifyAuditPaneBranchNotTakenIcon: 'red' 
FortifyAuditPaneDefaultIcon: 'blue' 
FortifyAuditPaneJumpIcon : 'yellow' 
FortifyAuditPaneFriorityLow: 'yellow'
FortifyAuditPaneFriorityMedium: 'light_orange'
FortifyAuditPaneFriorityHigh: 'dark_orange'
FortifyAuditPaneFriorityCritical: 'blue'

FortifyTestPaneCmd: '@Comment'
FortifyTestPaneFile: '@Title'
FortifyTestPanePassed: 'green'
FortifyTestPaneFailed: 'red'

FortifyCategoryMapping: '@Title'

FortifyDefinitionCharacterizationProperty: '@Tag'
FortifyDefinitionLineComment: '@Comment'
FortifyDefinitionComment: '@Comment'
FortifyDefinitionString1: '@String'
FortifyDefinitionString2: '@String'
FortifyDefinitionTaintFlag: '@Function'
FortifyDefinitionTaintSign: '@Identifier'
FortifyDefinitionTaintOperator: '@Identifier'
FortifyDefinitionForeachKeyword: '@Tag'

FortifyDescriptionPlaintext: '@Function'
FortifyDescriptionXMLAttribute: '@Function' 
FortifyDescriptionPreString: 'white' 

FortifyNSTSourceinfo: '@Comment'
FortifyNSTOperator: '@PreProc'
FortifyNSTString: '@String'
FortifyNSTType: '@Type'

FortifyRulepackRuleIDDash: '@Identifier'
FortifyRulepackRuleIDChars: '@Function'
FortifyRulepackTaintFlagSign: '@Identifier'
FortifyRulepackTaintFlag: '@Function'
FortifyRulepackRegexpString: '@Identifier'
FortifyRulepackRegexpBoundary: '@Identifier'
FortifyRulepackRegexpQuantifier: '@Identifier'
FortifyRulepackRegexpOr: '@Identifier'
FortifyRulepackRegexpMod: '@Identifier'
FortifyRulepackRegexpBackRef: '@Identifier'
FortifyRulepackRegexpGroup: '@Identifier'
FortifyRulepackRegexpCharClass: '@Identifier'

FortifyStructuralType: '@Tag'
FortifyStructuralString: '@String'
FortifyStructuralOperator: '@Identifier'
FortifyStructuralMatches: '@Identifier'
FortifyStructuralVariable: '@Type'
FortifyStructuralLineComment: '@Comment'
FortifyStructuralComment: '@Comment'
FortifyStructuralRegexpString: '@Identifier'
FortifyStructuralRegexpBoundary: '@Identifier'
FortifyStructuralRegexpQuantifier: '@Identifier'
FortifyStructuralRegexpOr: '@Identifier'
FortifyStructuralRegexpMod: '@Identifier'
FortifyStructuralRegexpBackRef: '@Identifier'
FortifyStructuralRegexpGroup: '@Identifier'
FortifyStructuralRegexpCharClass: '@Identifier'
