htmlItalic: 'lightest_grey'
htmlTag: 'lightest_grey' # Function
htmlEndTag: 'lightest_grey' # Identifier
htmlArg: 'dark_orange' # Type
htmlTagName: 'light_blue' # htmlStatement
htmlSpecialTagName: 'blue' # Exception
htmlValue: '' # String
htmlH1: 'light_orange' # Title
htmlH2: '' # htmlH1
htmlH3: '' # htmlH2
htmlH4: '' # htmlH3
htmlH5: '' # htmlH4
htmlH6: '' # htmlH5
htmlHead: '' # PreProc
htmlTitle: 'purple' # Title
htmlBoldItalicUnderline: '' # htmlBoldUnderlineItalic
htmlUnderlineBold: '' # htmlBoldUnderline
htmlUnderlineItalicBold: '' # htmlBoldUnderlineItalic
htmlUnderlineBoldItalic: '' # htmlBoldUnderlineItalic
htmlItalicUnderline: '' # htmlUnderlineItalic
htmlItalicBold: '' # htmlBoldItalic
htmlItalicBoldUnderline: '' # htmlBoldUnderlineItalic
htmlItalicUnderlineBold: '' # htmlBoldUnderlineItalic
htmlLink: '' # Underlined
htmlLeadingSpace: '' # None
htmlPreStmt: '' # PreProc
htmlPreError: '' # Error
htmlPreProc: '' # PreProc
htmlPreAttr: '' # String
htmlPreProcAttrName: '' # PreProc
htmlPreProcAttrError: '' # Error
htmlSpecial: '' # Special
htmlSpecialChar: '' # Special
htmlString: 'yellow' # String
htmlStatement: '' # Statement
htmlComment: '' # Comment
htmlCommentPart: '' # Comment
htmlCommentError: '' # htmlError
htmlTagError: '' # htmlError
htmlEvent: 'dark_orange' # javaScript
htmlError: '' # Error
javaScript: '' # Special
javaScriptExpression: '' # javaScript
htmlCssStyleComment: '' # Comment
htmlCssDefinition: '' # Special
