rubyBlockParameterList: 'white'
rubyInterpolation: 'lighter_green'
rubyClass: 'dark_orange' # rubyDefine
rubyModule: '@rubyClass' # rubyDefine
rubyMethodExceptional: '' # rubyDefine
rubyDefine: '' # Define
rubyFunction: '' # Function
rubyConditional: '' # Conditional
rubyConditionalModifier: '' # rubyConditional
rubyExceptional: '' # rubyConditional
rubyRepeat: '' # Repeat
rubyRepeatModifier: '' # rubyRepeat
rubyOptionalDo: '' # rubyRepeat
rubyControl: '' # Statement
rubyInclude: '' # Include
rubyInteger: '' # Number
rubyASCIICode: '' # Character
rubyFloat: '' # Float
rubyBoolean: '' # Boolean
rubyException: '' # Exception
rubyIdentifier: '' # Identifier
rubyClassVariable: '' # rubyIdentifier
rubyConstant: '' # Type
rubyGlobalVariable: '@rubyInstanceVariable' # rubyIdentifier
rubyBlockParameter: 'lightest_grey' # rubyIdentifier
rubyInstanceVariable: 'lightest_grey' # rubyIdentifier
rubyPredefinedIdentifier: '' # rubyIdentifier
rubyPredefinedConstant: '' # rubyPredefinedIdentifier
rubyPredefinedVariable: '' # rubyPredefinedIdentifier
rubySymbol: 'dark_pink' # Constant
rubyKeyword: '' # Keyword
rubyOperator: '' # Operator
rubyBeginEnd: '' # Statement
rubyAccess: 'purple' # Statement
rubyAttribute: '' # Statement
rubyEval: '' # Statement
rubyPseudoVariable: '' # Constant
rubyComment: '' # Comment
rubyData: '' # Comment
rubyDataDirective: '' # Delimiter
rubyDocumentation: '' # Comment
rubyTodo: '' # Todo
rubyQuoteEscape: '' # rubyStringEscape
rubyStringEscape: '' # Special
rubyInterpolationDelimiter: 'white' # Delimiter
rubyNoInterpolation: '' # rubyString
rubySharpBang: '' # PreProc
rubyRegexpDelimiter: 'light_green' # rubyStringDelimiter
rubySymbolDelimiter: '' # rubyStringDelimiter
rubyStringDelimiter: '' # Delimiter
rubyHeredoc: '' # rubyString
rubyString: '' # String
rubyRegexpEscape: 'light_green' # rubyRegexpSpecial
rubyRegexpQuantifier: 'light_green' # rubyRegexpSpecial
rubyRegexpAnchor: 'light_green' # rubyRegexpSpecial
rubyRegexpDot: '' # rubyRegexpCharClass
rubyRegexpCharClass: 'light_green' # rubyRegexpSpecial
rubyRegexpSpecial: 'light_green' # Special
rubyRegexpComment: '' # Comment
rubyRegexp: 'light_green' # rubyString
rubyInvalidVariable: '' # Error
rubyError: '' # Error
rubySpaceError: '' # rubyError
